### ISSUE TITLE
[BM29.subtract] Handle the case when a single buffer is provided

### ISSUE THREAD

**Issue by kif** [kif/dahu#77]
An error like this was seen:
```'Warning in SubtractBuffer: Processing failed and unable to send remaining data to ISPyB: <class \'AttributeError\'> \'NoneType\' object has no attribute \'radial\'Traceback (most recent call last):  File "/usr/lib/python3/dist-packages/dahu/plugins/bm29/subtracte.py", line 161, in process    self.create_nexus()  File "/usr/lib/python3/dist-packages/dahu/plugins/bm29/subtracte.py", line 260, in create_nexus    tomerge = get_equivalent_frames(proba, fidelity, fidelity)  File "/usr/lib/python3/dist-packages/dahu/plugins/bm29/common.py", line 149, in get_equivalent_frames    ext_diag[0] = ext_diag[1]IndexError: index 1 is out of bounds for axis 0 with size 1During handling of the above exception, another exception occurred:Traceback (most recent call last):  File "/usr/lib/python3/dist-packages/dahu/plugins/bm29/subtracte.py", line 166, in process    self.send_to_ispyb()  File "/usr/lib/python3/dist-packages/dahu/plugins/bm29/subtracte.py", line 734, in send_to_ispyb    ispyb.send_subtracted(self.to_pyarch)  File "/usr/lib/python3/dist-packages/dahu/plugins/bm29/ispyb.py", line 299, in send_subtracted    sub = self.save_curve("subtracted", subtracted, basename, gallery=True)  File "/usr/lib/python3/dist-packages/dahu/plugins/bm29/ispyb.py", line 228, in save_curve    sasl = numpy.vstack((integrate_result.radial, integrate_result.intensity, integrate_result.sigma))AttributeError: \'NoneType\' object has no attribute \'radial\''
```

**Comment by kif** [comment]
has been fixed
